version: '3'

services:
 api: # Node.js App
  container_name: slime-marketplace-backend-api
  image: slimenetwork/slime-marketplace-backend-api:latest
  build: .
  ports:
   - '5233:5233' # Expose API port
   - '9229:9229' # Expose Node process debug port (disable in production)
  environment: # Set ENV vars
   - NODE_ENV=local
   - ES_HOST=elasticsearch
   - PORT=5233
  volumes: # Attach local game data directory
   - ./games:/usr/src/app/games
   - ./public:/usr/src/app/public

 elasticsearch: # Elasticsearch Instance
  container_name: marketplace-search
  image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
  volumes: # Persist ES data in separate "esdata" volume
   - esdata:/usr/share/elasticsearch/data
  environment:
   - xpack.security.enabled=false
   - bootstrap.memory_lock=false
   - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
   - discovery.type=single-node
  ports: # Expose Elasticsearch ports
   - '9300:9300'
   - '9200:9200'

volumes: # Define seperate volume for Elasticsearch data
 esdata:
